services:
  web:
    image: python:3.13-slim
    container_name: django_app
    volumes:
      - ./app:/app
    working_dir: /app
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"  # Порт для отладки
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1