services:
  web:
    image: python:3.13-slim
    container_name: django_app
    volumes:
      - ./app:/app
    working_dir: /app
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"  # Порт для отладки
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    command: >
    sh -c "pip install -r requirements.txt &&
            python manage.py runserver 0.0.0.0:8000"    
        
    #entrypoint: ['/app/entrypoint.sh']
    # command: >
    # sh -c "python manage.py runserver 0.0.0.0:8000"
    #   sh -c "pip install -r requirements.txt &&
    #         tail -f /dev/null"
    # command: >
    #   sh -c "pip install -r requirements.txt &&
    #         python manage.py runserver --noreload 0.0.0.0:8000"
