# Generated by Django 5.1.6 on 2025-03-06 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 20, 51, 17, 703099)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидание', 'В ожидании'), ('выполнен', 'Выполнен')], default='В ожидании', max_length=50),
        ),
    ]
